sudo: required

services:
  - docker

script: 
  - docker login -u jamesemwallis -p $PASSWORD
  - travis_wait 50 docker build -t artistjodi .  
  - docker tag artistjodi jamesemwallis/artistjodi:latest
  - docker push jamesemwallis/artistjodi:latest