sudo: required

services:
  - docker

script: 
  - docker login $USERNAME $PASSWORD
  - docker build -t artistjodi . 
  - docker tag artistjodi jamesemwallis/artistjodi:latest
  - docker push jamesemwallis/artistjodi:latest